apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "data-tag.fullname" . }}-flyway-service"
  labels:
     {{- include "data-tag.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  ttlSecondsAfterFinished: 6000
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: flyway-service
          image: "{{ .Values.image.repository }}:flyway-service-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: DB_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.database.password | quote }}
